language: cpp
os:
  - linux
compiler:
  - gcc
sudo: required
dist: trusty
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
  - sudo apt-get -qq update
  - sudo apt-get -qq install catch
  - sudo apt-get -qq install libarmadillo-dev
  - sudo apt-get -qq install libboost-all-dev
  - sudo apt-get -qq install libhdf5-dev
  - sudo apt-get -qq install qt56-meta
  - sudo apt-get -qq install qt563d
  - sudo apt-get -qq install qt56declarative
  - sudo apt-get -qq install libboost-dev
  - sudo apt-get -qq install gcc-5
  - sudo apt-get -qq install g++-5
  - sudo apt-get -qq install libpugixml-dev
  - sudo mv /usr/bin/gcc /usr/bin/gcc-old
  - sudo mv /usr/bin/g++ /usr/bin/g++-old
  - sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
script:
  - dpkg -L g++-5
  - source /opt/qt56/bin/qt56-env.sh
     && mkdir build
     && cd build
     && /opt/qt56/bin/qmake .. CONFIG=trusty
     && make
     && cd tests
     && cd auto
     && ./auto
