language: cpp
os:
  - linux
compiler:
  - gcc
sudo: required
services: docker
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: XWZ6IEeCqMrnEqf1jqgS6j2XFC0qsIDsNmI+aJfIBhLcG+Zo7pbEdownrnSLa4P2UxgBWN1YepQbAegOZavleF7/+eBKBAuxKx3tTyCtsaAWsvPHhuxryg8VNnRNzHzQVTqDzJfekTw/9yNDGYPtzxtD0e+8jwAHqLdFdtEFHRc=
before_install:
    - docker build -t dragly/photonflow -f .docker/Dockerfile .
script:
    - docker run dragly/photonflow bash -c "/opt/qt57/bin/qmake photonflow.pro && make -j8 && cd tests/auto && ./auto"
